package modelo;
// Generated 08-22-2017 09:02:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int iddepartamento;
     private Zona zona;
     private String nombredepartamento;
     private Set<Municipio> municipios = new HashSet<Municipio>(0);
     
     
     ////////
      private int idzona;
      

    public Departamento() {
    }

	
    
      ///////////////////////
    public Departamento(int idDepto, int idZona, String nombreDepto) {
        this.iddepartamento = idDepto;
        this.idzona = idZona;
        this.nombredepartamento = nombreDepto;
    }
    
        public Departamento(int idDepto, Zona zona, String nombreDepto) {
        this.iddepartamento = idDepto;
        this.zona =zona;
        this.nombredepartamento= nombreDepto;
    }
/////////////////
        
        
        
        
    public Departamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public Departamento(int iddepartamento, Zona zona, String nombredepartamento, Set<Municipio> municipios) {
       this.iddepartamento = iddepartamento;
       this.zona = zona;
       this.nombredepartamento = nombredepartamento;
       this.municipios = municipios;
    }
   
    public int getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public Zona getZona() {
        return this.zona;
    }
    
    public void setZona(Zona zona) {
        this.zona = zona;
    }
    public String getNombredepartamento() {
        return this.nombredepartamento;
    }
    
    public void setNombredepartamento(String nombredepartamento) {
        this.nombredepartamento = nombredepartamento;
    }
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }




}


