package modelo;
// Generated 08-22-2017 09:02:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zona generated by hbm2java
 */
public class Zona  implements java.io.Serializable {


     private int idzona;
     private String nombrezona;
     private Set<Departamento> departamentos = new HashSet<Departamento>(0);

    public Zona() {
    }

    
        // *************
    
    public Zona(int idZona, String nombreZona) {    
        this.idzona = idZona;
        this.nombrezona = nombreZona;
    }

    //*********
    
    
	
    public Zona(int idzona) {
        this.idzona = idzona;
    }
    public Zona(int idzona, String nombrezona, Set<Departamento> departamentos) {
       this.idzona = idzona;
       this.nombrezona = nombrezona;
       this.departamentos = departamentos;
    }
   
    public int getIdzona() {
        return this.idzona;
    }
    
    public void setIdzona(int idzona) {
        this.idzona = idzona;
    }
    public String getNombrezona() {
        return this.nombrezona;
    }
    
    public void setNombrezona(String nombrezona) {
        this.nombrezona = nombrezona;
    }
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }




}


